### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by titilambert** [kk7ds/somecomfort#11]
Hello !
Do you plan to create a new release on Pypi ?
Thanks !

**Comment by kk7ds** [comment]
Yeah, I'll try to do that today.

**Comment by kk7ds** [comment]
I forgot I had done 0.3.2 recently. That release has everything currently in the repo as far as I can tell. What else were you looking for?

**Comment by titilambert** [comment]
Hello, Pypi says that version 0.3.2 was released on 2016-09-23. But the last commit was on novembre 2016 (https://pypi.python.org/pypi/somecomfort/0.3.2). It's hard to say, because there is no tags on github since version 0.2.1 .

**Comment by kk7ds** [comment]
Doh, sorry, I totally forgot to pull locally after merging your two PRs and thus forgot that anything had changed.

I just pushed 0.4.0 up to pypi. Thanks for the reminder!
