### ISSUE TITLE
Issues with Honeywell Thermostat for Home Assistant

### ISSUE THREAD

**Issue by sgauche** [kk7ds/somecomfort#2]
Please see the issues I submitted on the Home Assistant GitHub page:
https://github.com/home-assistant/home-assistant/issues/2794

Thanks!

**Comment by texnofobix** [comment]
Auto mode seems to be "SystemSwitchPosition":5

**Comment by texnofobix** [comment]
Heat: 1
Off: 2
Cool: 3
Auto: 4 then switches to 5.
