### ISSUE TITLE
Please choose a license for redistribution

### ISSUE THREAD

**Issue by onkelbeh** [kk7ds/somecomfort#27]
Hi,

first, thanks for your work. I would like to use your integration for my Home Assistant Gentoo overlay, https://github.com/onkelbeh/HomeAssistantRepository/

You have not published a license, not here, and not on pypi, so i am asking for clarification.

According to Gentoo's license guidelines, it is not allowed to redistribute a package without a license (https://devmanual.gentoo.org/general-concepts/licenses/index.html).

Thanks a lot in advance.
 \B.

**Comment by gonzotek** [comment]
This was recently added by kk7ds in response to another issue 
Issue: https://github.com/kk7ds/somecomfort/issues/33
Commit: https://github.com/kk7ds/somecomfort/pull/34

**Comment by onkelbeh** [comment]
Thanks.
