### ISSUE TITLE
somecomfort: error: unrecognized arguments: --devices

### ISSUE THREAD

**Issue by pancho-villa** [kk7ds/somecomfort#3]
I think this switch --devices has been deprecated, but it's still in the readme.

$ somecomfort --username MYUSER --password MYPASSWORD --login
Success
$ somecomfort --devices
usage: somecomfort [-h] [--get_setpoint_cool]
                   [--set_setpoint_cool SET_SETPOINT_COOL]
                   [--get_setpoint_heat]
                   [--set_setpoint_heat SET_SETPOINT_HEAT] [--get_fan_mode]
                   [--set_fan_mode SET_FAN_MODE] [--get_system_mode]
                   [--set_system_mode SET_SYSTEM_MODE]
                   [--get_current_temperature] [--cancel_hold]
                   [--permanent_hold] [--hold_until HOLD_UNTIL] [--get_hold]
                   [--username USERNAME] [--password PASSWORD]
                   [--device DEVICE] [--login]
somecomfort: error: unrecognized arguments: --devices

**Comment by ghost** [comment]
I just came here to say the same thing :)
