### ISSUE TITLE
The Honeywell API on which this is based?

### ISSUE THREAD

**Issue by glyndon** [kk7ds/somecomfort#40]
Can you provide a link to whatever API document permitted you to create somecomfort? 

(or did you do it by, e.g., reverse-engineering the webpage?)
I can't find any developer information at the Honeywell site.

Thanks.

**Comment by kk7ds** [comment]
Yeah, and you probably won't :) This code was reverse-engineered from the browser client. AFAIK Honeywell doesn't publish anything to help.

**Comment by glyndon** [comment]
Thanks. I figured it probably was reverse-engineered.
All I can find are these two pages, but can't find the "home" page that leads to (and explains) either of them, so am not clear if either one pertains to the MyTotalComfort product line, or to the Resideo line only.
https://developer.honeywellhome.com/user/register
https://mytotalconnectcomfort.com/WebApi/Help/LogIn?ReturnUrl=%2FWebApi%2FHelp
